{{- with .Values.config.oidc }}
{{- if .secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
type: Opaque
data:
{{- with .clientID }}
  clientID: {{ . | b64enc | quote }}
{{- end }}
{{- with .clientSecret }}
  clientSecret: {{ . | b64enc | quote }}
{{- end }}
{{- with .issuerURL }}
  issuerURL: {{ . | b64enc | quote }}
{{- end }}
{{- with .scopes }}
  scopes: {{ . | b64enc | quote }}
{{- end }}
{{- with .callbackURL }}
  callbackURL: {{ . | b64enc | quote }}
{{- end }}
{{- with .validatorClientID }}
  validatorClientID: {{ . | b64enc | quote }}
{{- end }}
{{- with .validatorIssuerURL }}
  validatorIssuerURL: {{ . | b64enc | quote }}
{{- end }}
{{- with .useAccessToken }}
  useAccessToken: {{ . | toString | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
